notifications:
  email: false
  slack:
    secure: udBNS/g6ByMQI+F2ub54cpFvE73xmfSAki6fRlSid3K+qK6t9wibZGWMlvUgnFz76if4P5VWn9571kbkWlRsYGwGtj6TUYUek/L+ofDi3qNPmed4aMiCcUyltHBKWcuUGFOcFL2ybAFnvggoWFj5kPJtjarsyamc5cbF/JvcujU=

language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y clang gcc-4.8 g++-4.8 libgsl0-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - wget http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz
  - tar xvzf nlopt-2.4.2.tar.gz
  - cd nlopt-2.4.2
  - ./configure --prefix=/usr --enable-shared && make && sudo make install
  - cd ..

script:
  - make test

compiler:
  - clang
  - gcc
